### ISSUE TITLE
Why no default driver?

### ISSUE THREAD

**Issue by samwilson** [kohana/cache#48]
Most modules have a default basic working configuration set. For this module, that could be the `file` cache (given that the directory it uses is used by Kohana core). Is there a reason that there's no default driver?

Thanks!

**Comment by shadowhand** [comment]
I'm not quite sure what you mean... we have [several default drivers](https://github.com/kohana/cache/tree/3.3/master/classes/Kohana/Cache).

**Comment by samwilson** [comment]
Oh, no I mean: none are active by default in the [`config/cache.php`](https://github.com/kohana/cache/blob/3.3/master/config/cache.php) file (they're all commented out).

**Comment by shadowhand** [comment]
Ah yes. Module configuration is typically meant to be an example, not actually provide defaults. See database, etc.

**Comment by samwilson** [comment]
Really? I've never thought about them like that! I've always thought that the whole point of [config merging](http://kohanaframework.org/3.3/guide/kohana/config#config-merging) is that modules can provide a default, and higher levels of configuration can be applied on top.

Oh, and the [database config](https://github.com/kohana/database/blob/3.3/master/config/database.php) does set values; the cache one is the only one I've ever seen that has everything commented out.

It sort of makes sense: if one needs to specify a config value, do so, but otherwise it gets pulled from further down the cascading file system.

**Comment by shadowhand** [comment]
Database really only has default values for legacy reasons. It's hard to say that file cache (or any of the others) is an appropriate default for the module.
