### ISSUE TITLE
Cache TTL may produce unexpected behaviour, and has a flickering test

### ISSUE THREAD

**Issue by acoulton** [kohana/cache#50]
As observed in kohana/kohana#41, it seems like one of the inherited test in Kohana_Cache_FileTest may be flickering if the execution runs across two seconds.

The test case in [CacheBasicMethodsTest](https://github.com/kohana/cache/blob/3.4/develop/tests/cache/CacheBasicMethodsTest.php#L106) appears to specify that:
- When ->set is called with a value and TTL 0
- And the test does not wait between set and get
- Then ->get should return the cached value

The [File driver code](https://github.com/kohana/cache/blob/3.4/develop/classes/Kohana/Cache/File.php#L162) checks if a value has expired with the following test:

``` php
if (($created + (int) $lifetime) < time())
```

This usually passes the test, because the < means the value doesn't expire till the end of the second it was set in - but if the test happens to start late in a second so that the get falls into the next second it will fail.

Obviously we need to make the test cope with second boundaries, but I think there's a bigger issue in that I would expect a TTL of 0 to mean "this expires immediately" / "don't cache this at all".

My hunch is that many of the native drivers would fail this test every time. Currently most of their tests are skipped on travis, and APC's TTL support is broken in CLI but I think it would probably also fail in a browser. I need to do a bit more investigation to see if I'm right.

If so, I think this is a bug in 3.3 and we should change the test so that:
- When ->set is called with a value and TTL 0
- And the test does not wait between set and get
- Then ->get should return the default value or NULL

And change the file driver so that it uses `<=` to check for expiry, so items expire at the beginning of the second when their lifetime is up, not the end.

Thoughts?

**Comment by enov** [comment]
I think the issue is bigger than a test flicker.

In the cases of `Cache_Memcache`, `Cache_Memcached`, `Cache_APC`, `Cache_SQLite` and `Cache_Wincache` a `TTL` value of `0` means that the cache will never expire.

And that's why almost all the tests for caching have a `TTL` value of `0`.

I think this is an implementation bug in the `Cache_File`. Also, the abstract `Kohana_Cache` class documentation, as well as Kohana's documentation should make clear that a `TTL` value of `0` means that the cache will never expire.

**Comment by acoulton** [comment]
@enov my bad, yes of course TTL 0 should == 'never expire', not 'expire now'. This is definitely a bug in Cache_File.

If anyone is explicitly relying on TTL 0 meaning "cache till the end of this second" - then when we fix this it will produce unexpected side effects in their apps. I presume it's safe to assume that's such an odd thing to do that it's unlikely to be a problem?

**Comment by enov** [comment]
Yes, I believe it is safe to assume that, and that's unlikely to create a problem when we fix :)

**Comment by enov** [comment]
@acoulton do you want me to try to fix this? or did you start working on it already?

**Comment by acoulton** [comment]
I can take a look later today.

**Comment by enov** [comment]
Alright

**Comment by enov** [comment]
@acoulton Would you like me to take this?

**Comment by acoulton** [comment]
Oops, sorry. Yes, if you have time :)
