### ISSUE TITLE
Default cache behavior inconsistent

### ISSUE THREAD

**Issue by ralfonso-directnic** [kohana/cache#63]
The docs are a little unclear on cache behavior and the code has a potential to cause confusing behavior

From comment in Cache.php#L52

In cases where only one cache group is required, if the group is named default there is no need to pass the group name when instantiating a cache instance. (To me at least this reads as Cache::instance() == Cache::instance("default") )

From user guide

```
 $cache = Cache::instance();
```

The default group will use whatever is set to [Cache::$default] and must have a corresponding [configuration](cache.config) definition for that group

The code actually supports the 2nd statement, I'd suggest either removing or clarifying the first block or setting Cache::$default in Cache.php to "default" instead of "file" especially since the config ship's commented out you are not leaving anything in a broken state.

**Comment by enov** [comment]
Thanks sir. Fixed in 16d4ea4. Will be available when `3.3.3` is out. If still not clear please reopen.
