### ISSUE TITLE
Bug in MemCache module

### ISSUE THREAD

**Issue by smile1980** [kohana/cache#69]
class Kohana_Cache_Memcache extends Cache implements Cache_Arithmetic {

line 216

```
public function set($id, $data, $lifetime = 3600)
{

    // If the lifetime is greater than the ceiling
    if ($lifetime > Cache_Memcache::CACHE_CEILING)
    {
        // Set the lifetime to maximum cache time
        $lifetime = Cache_Memcache::CACHE_CEILING + time();
    }
    // Else if the lifetime is greater than zero
    elseif ($lifetime > 0)
    {
        $lifetime += time();
    }
    // Else
    else
    {
        // Normalise the lifetime
        $lifetime = 0;
    }

    return $this->_memcache->set($this->_sanitize_id($id), $data, $this->_flags, $lifetime);
}
```

//error
$lifetime = Cache_Memcache::CACHE_CEILING + time();
$lifetime += time();

+time() not necessary this;
http://php.net/manual/ru/memcache.set.php

expire

Expiration time of the item. If it's equal to zero, the item will never
expire. You can also use Unix timestamp or a number of seconds starting from
current time, but in the latter case the number of seconds may not exceed
2592000 (30 days).

**Comment by enov** [comment]
Hey @smile1980! Yeah, I remember that code got me too, at some point...

But it is running fine, using Unix timestamp (adding the lifetime to the timestamp) for expire, according to the specs you pasted here.
